# Generated by Django 4.2.16 on 2025-04-17 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='customerreview',
            old_name='is_featured',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='customerreview',
            old_name='date_added',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
