# Generated by Django 4.2.16 on 2025-06-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gift_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
