# Generated by Django 4.2.16 on 2025-06-09 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
        ('products', '0003_product_is_gift_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='validity_period',
            field=models.IntegerField(blank=True, help_text='Validity period in months (for gift cards only)', null=True),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remaining_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expiry_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.order')),
            ],
        ),
    ]
